---
name: Deploy LZ
on:
push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  whatif:
    name: What If
    runs-on:
      ubuntu-latest
    concurrency: mgmt-tfstate
    environment: alz-mgmt-plan
    permissions:
      id-token: write
      contents: read
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-variables@main
        with:
          parameters_file_name: ${{ env.PARAMETERS_FILE_NAME }}

      - name: Get On Demand Folder infra-as-code
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-on-demand-folder@main
        with:
          repository: "https://github.com/Azure/ALZ-Bicep"
          releaseArtifactName: "accelerator.zip"
          releaseVersion: "${{ env.RELEASE_VERSION }}"
          sourcePath: "infra-as-code"
          targetPath: "infra-as-code"


      - name: Install Bicep and Update Az Module
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: First Deployment Check
        id: firstDeploymentCheck
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-first-deployment-check@main
        if: ${{ !inputs.destroy }}
        with:
          managementGroupId: ${{ env.MANAGEMENT_GROUP_ID }}

      - name: 'What If: Management Groups Deployment'
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.management_groups && !inputs.destroy }}
        with:
          displayName: 'Management Groups Deployment'
          templateFilePath: './infra-as-code/bicep/modules/managementGroups/managementGroupsScopeEscape.bicep'
          templateParametersFilePath: './config/custom-parameters/managementGroups.parameters.all.json'
          managementGroupId: '${{ env.ROOT_PARENT_MANAGEMENT_GROUP_ID }}'
          subscriptionId: ''
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'true'
          firstDeployment: '${{ env.firstDeployment }}'
          whatIfEnabled: 'true'
      